// Oferta confirmada por Alicia el 4 de octubre de 2026.
export const courses = [
  { id: 'a1', level: 'A1', title: 'Italiano desde cero',
    introduction: 'Tu primera conversación en italiano empieza acá.',
    description: 'Aprendé a presentarte, hablar de tu rutina y comunicarte en situaciones cotidianas con el acompañamiento de Alicia.',
    topics: ['Saludos y presentaciones', 'La familia y la vida cotidiana', 'Vocabulario y presente indicativo', 'Lectura, escucha y diálogos sencillos'],
    materials: 'Manual comunicativo, actividades y recursos para practicar entre clases.' },
  { id: 'a2', level: 'A2', title: 'Italiano para la vida cotidiana',
    introduction: 'Dale más herramientas a lo que ya sabés.',
    description: 'Practicá cómo desenvolverte en un restaurante, hacer compras, pedir información y contar experiencias. Partimos de situaciones reales para comprender y usar la gramática.',
    topics: ['Al bar y al restaurante', 'Compras, cantidades y recetas', 'Pedidos y respuestas con cortesía', 'Situaciones y videos con Vittoria'],
    materials: 'Unidades didácticas, diálogos, videos y ejercicios de práctica.' },
  { id: 'conversacion', level: 'Conversación', title: 'Conversazione in italiano',
    introduction: 'Animarte a hablar también se practica.',
    description: 'Un espacio de conversación guiada para quienes ya tienen una base de italiano y quieren ganar confianza, ampliar vocabulario y disfrutar de la cultura italiana.',
    topics: ['Viajes y vida cotidiana', 'Cine, música y cultura italiana', 'Opiniones y experiencias personales', 'Temas que proponen los estudiantes'],
    materials: 'Textos, vocabulario y disparadores para participar en cada encuentro.' },
] as const

export const materials = [
  { id: 'manual-a1', tag: 'Manual A1', title: 'Manual de italiano A1',
    description: 'Tu material para empezar desde cero y trabajar el italiano a partir de situaciones cotidianas, con lectura, vocabulario, gramática y actividades.',
    price: { ars: 19900, usd: 13, launchOffer: false },
    features: ['Enfoque comunicativo', 'Actividades para practicar', 'Recursos para acompañar las clases'],
    action: 'Consultar por el manual', href: '/#contacto' },
  { id: 'lectura-a1', tag: 'Lectura A1', title: 'Un’argentina in Italia', subtitle: 'Una nuova vita a Roma',
    description: 'Acompañá a Vittoria en una historia que une Mendoza e Italia. Una lectura ilustrada para practicar italiano a tu ritmo.',
    price: { ars: 9900, usd: 10, launchOffer: true },
    features: ['Capítulos ilustrados', 'Audios para acompañar la lectura', 'Actividades, vocabulario y soluciones'],
    action: 'Consultar por el libro', href: '/#contacto' },
  { id: 'unidades-a2', tag: 'Recursos A2', title: 'Unidades de italiano A2',
    description: 'Situaciones, diálogos y actividades para seguir usando el italiano en la vida cotidiana, como complemento de tus clases con Alicia.',
    features: ['Enfoque comunicativo', 'Videos y situaciones cotidianas', 'Actividades para reforzar lo aprendido'],
    action: 'Consultar por las unidades A2', href: '/#contacto' },
  { id: 'guia', tag: 'Recurso gratuito', title: 'Tu primer paso en italiano',
    description: 'Una guía para empezar desde cero: palabras útiles, pronunciación, errores frecuentes y un plan de práctica.',
    features: ['Vocabulario inicial', 'Consejos de pronunciación', 'Práctica para empezar'],
    action: 'Leer la guía gratuita', href: '/guia-italiano/' },
] as const
