// Oferta confirmada por Alicia el 4 de octubre de 2026.
export const courses = [
  { id: 'a1', level: 'A1', title: 'Italiano desde cero',
    introduction: 'Tu primera conversación en italiano empieza acá.',
    description: 'Aprendé a presentarte, hablar de tu rutina y comunicarte en situaciones cotidianas con el acompañamiento de Alicia.',
    topics: ['Saludos y presentaciones', 'La familia y la vida cotidiana', 'Vocabulario y presente indicativo', 'Lectura, escucha y diálogos sencillos'],
    materials: 'Manual comunicativo y actividades para practicar entre clases.' },
  { id: 'a2', level: 'A2', title: 'Italiano para la vida cotidiana',
    introduction: 'Dale más herramientas a lo que ya sabés.',
    description: 'Practicá cómo desenvolverte en un restaurante, hacer compras, pedir información y contar experiencias. Partimos de situaciones reales para comprender y usar la gramática.',
    topics: ['Al bar y al restaurante', 'Compras, cantidades y recetas', 'Pedidos y respuestas con cortesía', 'Situaciones y videos con Vittoria'],
    materials: 'Unidades didácticas, diálogos, videos y ejercicios de práctica.' },
  { id: 'conversacion', level: 'Conversación', title: 'Conversazione in italiano',
    introduction: 'Animarte a hablar también se practica.',
    description: 'Un espacio de conversación guiada para quienes ya tienen una base de italiano y quieren ganar confianza, ampliar vocabulario y disfrutar de la cultura italiana.',
    topics: ['Viajes y vida cotidiana', 'Cine, música y cultura italiana', 'Opiniones y experiencias personales', 'Temas que proponen los estudiantes'],
    materials: 'Textos, vocabulario y disparadores para participar en cada encuentro.' },
] as const

export const materials = [
  { id: 'manual-a1', tag: 'Manual A1', title: 'Manual de italiano A1',
    cover: { src: '/images/libros/manual-a1.jpg', width: 1414, height: 2000, alt: 'Portada de Italiano A1 per studenti internazionali, de Alicia Alejandra Tapia' },
    video: { id: '2FsKmQyugsk', title: 'Presentación del manual A1' },
    description: 'Tu material para empezar desde cero y trabajar el italiano a partir de situaciones cotidianas, con lectura, vocabulario, gramática y actividades.',
    price: { ars: 19900, usd: 13, launchOffer: false },
    features: ['Enfoque comunicativo', 'Actividades para practicar', 'Práctica para acompañar las clases'],
    action: 'Consultar por el manual', href: '/#contacto' },
  { id: 'lectura-a1', tag: 'Lectura A1', title: 'Un’argentina in Italia', subtitle: 'Una nuova vita a Roma',
    cover: { src: '/images/libros/un-argentina-in-italia.png', width: 1024, height: 1536, alt: 'Portada de Un’argentina in Italia: Vittoria en Roma con su maleta y cuaderno' },
    video: { id: 'nmiS8t67t0M', title: 'Presentación de la colección Un’argentina in Italia' },
    description: 'Acompañá a Vittoria en una historia que une Mendoza e Italia. Una lectura ilustrada para practicar italiano a tu ritmo.',
    price: { ars: 9900, usd: 10, launchOffer: true },
    features: ['Capítulos ilustrados', 'Audios para acompañar la lectura', 'Actividades, vocabulario y soluciones'],
    action: 'Consultar por el libro', href: '/#contacto' },
] as const
